### ISSUE TITLE
If nerdctl is installed, skip install and download.

### ISSUE THREAD

**Issue by mzwoelfer** [mzwoelfer/ansible-nerdctl#2]
Does check the version. But doesn't have logic to skip the install, if nerdctl exists.
- [ ] Also, if the found version is older than the defined one or latest from GitHub, overwrite aka update.

```YAML
- name: Check if nerdctl is already installed
  ansible.builtin.command: nerdctl --version
  ignore_errors: true
  become_user: "{{ ansible_user }}"
```
